### ISSUE TITLE
增加我参加的课程，我收藏的课程两个功能

### ISSUE THREAD

**Issue by fushang318** [mindpin/kc_courses#1]
### 功能描述

需要增加两个功能  
1. 我参加的课程
2. 我收藏的课程
### 需要完成的逻辑
1. 后台数据建模，和模型层逻辑，以及对应的测试
2. engline 内用来演示功能的逻辑完整的 controller 层逻辑和对应的 view（比如 我参加的课程列表页面，我收藏的课程列表页面）
3. 项目集成时用到的逻辑完整的 controller 层逻辑，以及对应的测试（比如 增加收藏 取消收藏 增加参加 取消参加 这四个 http api）

**Comment by destinyd** [comment]
好

**Comment by destinyd** [comment]
我参加的，已经完成，并提交代码
