### ISSUE TITLE
SimpleVideo，SimplePPT，SimplePDF 类型课件

### ISSUE THREAD

**Issue by fushang318** [mindpin/kc_courses#55]
file-part-upload 目前使用七牛的文档转码服务，已经实现了

```
word: doc, docx, odt, rtf, wps
ppt: ppt, pptx, odp, dps
excel: xls, xlsx, ods, csv, et
```

1 office三大文件家族（上面详细列出了具体文件类型） 文件转码成 pdf 和 一组图片
2 pdf 文件转码成 一组图片

我现在想先确认两个问题，你们给点建议

```
1 ware 的类型如何分
2 上传课件的界面做成什么样子
```

**ware 的类型如何分**

这个类型会记录在 ware 的 kind 字段，现在不确定该如何划分这几个类型
我提供几个方案啊，你们看看哪个合适

1 word ppt excel pdf audio video 
2 office pdf audio video
3 document audio video
4 以上类型的子集，比如 SimpleVideo，SimplePPT，SimplePDF

这个 kind 字段会影响到课件的呈现形式，以及用户对课件分类的预期，如何更好
比如 3 这种分类对呈现形式很友好，是否符合用户认知的分类，以及咱们是否需要全部支持这些类型

**上传课件的界面做成什么样子**

做成这样如何

在章节内，点击 "上传课件" 按钮，进入表单
![](http://i.teamkn.com/i/RotOcD1U.png)

文件类型如何不在支持范围内，提示”文件格式不支持“

点击确认，增加课件成功后，在课件列表中显示课件的类型和转码情况

**Comment by ben7th** [comment]
就三个呗
SimpleVideo 视频
SimpleAudio 音频
SimpleDocument 各种文档（转换流程都一样，就不分了）

**Comment by fushang318** [comment]
from  陈啸峰(DestinyD)

例如
class SimpleVideo < Ware
end

他父类是Ware
但是会在type字段记录下他的类型（SimpleVideo）
我们可以通过Ware.find 找到他，也能通过 SimpleVideo.find id 找到他

**Comment by fushang318** [comment]
模型如下

```
class SimpleVideoWare < Ware
  belongs_to :file_entity
end

class SimpleAudioWare < Ware
  belongs_to :file_entity
end

class SimpleDocumentWare < Ware
  belongs_to :file_entity
end
```

**Comment by fushang318** [comment]
优酷的视频上传流程
1
![](http://i.teamkn.com/i/XMubkqiS.png)

2
![](http://i.teamkn.com/i/FABoR0Sq.png)

3
![](http://i.teamkn.com/i/mzwai4T0.png)

1 先选择要上传的文件  
2 文件开始上传，显示进度条，同时可以填写名称和描述，确定按钮点不了，必须等上传完毕才可以  
3 文件上传完毕，可以点击确认来创建
