### ISSUE TITLE
课程需要进行的一些修改

### ISSUE THREAD

**Issue by fushang318** [mindpin/kc_courses#59]
1 课程封面字段目前保存的是图片url,需要改为保存 file entity id 
  如果没有指定封面时，字段为空，但是获取封面url的模型方法需要返回一个默认封面的url
  默认封面url以配置文件的形式提供
`config/application.yml`

``` yaml
development:
  course_default_cover_url: http://xxxx.xxx/xxx.png
```

---

2 课程需要增加 published_at 字段，用来保存最后一次发布的时间

---

3 课程需要增加一个统计方法，目前只用到视频，所以可以这么封装

``` ruby

course.statistic_info
# 返回的内容格式如下
{
  :video => {
    :count => "视频数量",
    :total_minute => "总分钟数，取整数"
  }
}
```

**Comment by destinyd** [comment]
@fushang318 
针对 1，添加了一个方法

``` ruby
# 有file_eneity则返回对应的url, 无，则返回ENV['course_default_cover_url']
def get_cover
end
```
